application:
  subdomain: foxel
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://foxel:80/
services:
  foxel:
    # ghcr.io/drizzletime/foxel:v1.4.0
    image: ghcr.1ms.run/drizzletime/foxel:v1.4.0
    environment:
      - TZ=Asia/Shanghai
      - SECRET_KEY={{stable_secret "foxel#secret_key"}}
      - TEMP_LINK_SECRET_KEY={{stable_secret "foxel#temp_link_secret_key"}}
    binds:
      - /lzcapp/var/data:/app/data
    setup_script: |
      mkdir -p /app/data/db
